### ISSUE TITLE
Build failure: CS8795 with dotnet 9.x - analyzer version mismatch

### ISSUE THREAD

**Issue by M-r-A** [rwmt/Multiplayer#970]
The build fails on all .NET 9.0.x SDKs with `CS8795` (partial method without implementation) due to an analyzer version incompatibility introduced in commit 075ab81.

### Summary

`SourceGen.csproj` depends on `Microsoft.CodeAnalysis.CSharp 5.3.0`, which requires Roslyn 5.3.0+. However:
- .NET SDK 9.0.x bundles Roslyn **4.14.0** ❌ (too old)
- .NET SDK 10.0.302+ bundles Roslyn **5.3.0+** ✓ (compatible)

The build workflow specifies `dotnet-version: 9.x`, so it triggers the mismatch locally for anyone building on 9.0.x.

### Steps to Reproduce

```bash
# On any .NET 9.0.x SDK (e.g., 9.0.315, 9.0.316):
dotnet build Source/Multiplayer.sln
```

### Expected Behavior

Build succeeds with warnings only.

### Actual Behavior

```
CSC : warning CS9057: Analyzer assembly 'SourceGen.dll' cannot be used because 
      it references version '5.3.0.0' of the compiler, which is newer than the 
      currently running version '4.14.0.0'.

D:/.../ChatCommandRegistry.cs(18,32): error CS8795: Partial method 
  'ChatCommandRegistry.Register(ChatCommandManager, MultiplayerServer)' 
  must have an implementation part because it has accessibility modifiers.

Build FAILED.
```

**Comment by notfood** [comment]
Why is 9.x needed?

**Comment by M-r-A** [comment]
> Why is 9.x needed?

This is from current CI
https://github.com/rwmt/Multiplayer/blob/899e359cf27b27e1fda11afac490df9d5a57cd2a/.github/workflows/build-workshop.yml#L23

**Comment by notfood** [comment]
Shouldn't we update that instead? To be honest, it's unused. I run the script locally and upload that. `build-workshop` isn't doing anything.

**Comment by M-r-A** [comment]
No objections to the update, but the scope of this issue is limited to the currently broken build. I want to solve that first, how's for you?
